# https://towardsdatascience.com/how-to-deploy-dbt-to-production-using-github-action-778bf6a1dff6
name: pr_to_main

on:
  push:
    branches:
      - main
env:
  DBT_PROFILES_DIR: ./

jobs:
  pr_to_main:
    name: pr_to_main
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: DuckDB setup
        uses: opt-nc/setup-duckdb-action@v1.0.8

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Lint with sqlfluff
        run: |
          pip install sqlfluff
          sqlfluff lint -r L020,L021,L049 --dialect ansi -v models/
    
          # Linting only modified models
          # git fetch origin main:main
          # git diff main --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint

      - name: Install dependencies
        run: |
          pip install dbt-duckdb
          dbt deps
      
      - name: Download Prior Dbt Artifacts
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          WORKFLOW_FILENAME: pr_to_main.yml
          ARTIFACT_NAME: dbt-target
          ARTIFACT_FILENAME: dbt-target.zip
          UNZIP_DIR: prior
        with:
          script: |
            const script = require('./scripts/download-previous-artifact.js')
            await script({github, context, core})    

      - name: Run dbt source freshness
        run: dbt source freshness

      - name: Run dbt build
        run: dbt build --select state:modified+ result:error+ source_status:fresher+ --defer --state prior

      - name: Run docs generate
        run: dbt docs generate

      - name: Upload Dbt Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dbt-target
          path: target

      - name: Download Dbt Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dbt-target

